name: Build, Test and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      - name: Run tests and collect coverage
        run: |
          dotnet test --no-build --configuration Release --logger trx --results-directory ./TestResults --collect:"XPlat Code Coverage"
          reportgenerator -reports:"**/coverage.cobertura.xml" -targetdir:"TestResults/report" -reporttypes:HtmlInline_AzurePipelines

      # - name: Upload test report to GitHub artifacts
      #   uses: actions/upload-artifact@v3.1.3
      #   with:
      #     name: test-report
      #     path: TestResults/report

      - name: Upload test report to FTP server
        uses: sebastianpopp/ftp-action@v1
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: "TestResults/report"
          remoteDir: "/"

      - name: Send test report via email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: ".NET Test Report - CI Pipeline"
          to: tester@example.com
          from: dotnet-pipeline@example.com
          content_type: text/html
          body: |
            <p>Hello Tester,</p>
            <p>Please find the attached test report generated during the latest deployment.</p>
            <p>Report Summary is attached.</p>
            <p>Regards,<br/>GitHub CI/CD</p>
          attachments: TestResults/report/index.html
